## Table of Contents

1. What is NumPy?
2. Why NumPy?
3. Key Concepts
4. Speed Comparison
5. NumPy Basics
   - Importing NumPy
   - Creating Arrays
   - Array Properties
   - Reshaping Arrays
   - Indexing & Slicing
   - Mathematical Operations
   - Aggregation Functions
   - Boolean Indexing
   - Broadcasting
   - Stacking Arrays
   - Copy vs View
6. NumPy Random Module
7. Summary


# 1. What is NumPy?

NumPy (Numerical Python) is the fundamental Python library for scientific computing. Its core is the ndarray — a fast, fixed-size, n-dimensional array of homogeneous elements (all same dtype). NumPy provides many fast, precompiled routines for math, linear algebra, FFT, random sampling, I/O, and array manipulation. Because heavy work is done in compiled C code, NumPy lets you write clear Pythonic code that runs at near-C speeds.

# 2. Why use NumPy instead of “traditional” Python lists?

• Speed — vectorized operations (no Python-level loops) run in optimized C code.

• Memory efficiency — arrays store values in contiguous memory with a single dtype, so less overhead than lists of Python objects.

• Convenience — element-wise arithmetic, reductions (sum/mean/std), slicing, reshaping, broadcasting, and linear algebra are   built in.

• Expressiveness — code resembles mathematical notation (e.g., c = a * b for element-wise multiply).

• Ecosystem — most scientific libraries (Pandas, SciPy, scikit-learn, etc.) expect/return NumPy arrays.

# 3. Key concepts

• Vectorization — write operations on whole arrays instead of writing Python loops. Fewer lines, fewer bugs, much faster.

• Broadcasting — NumPy can “stretch” smaller arrays to match the shape of bigger ones when the shapes are compatible, enabling concise code with scalars, vectors, and matrices.

• Homogeneous dtype — all elements same type → tight memory and fast CPU operations.

# 4. Example code — compare speed (pure Python vs NumPy)

In [1]:
import time, random
N = 2_000_000
a = [random.random() for _ in range(N)]
b = [random.random() for _ in range(N)]

#Python list multiply
t0 = time.time()
c = [a[i] * b[i] for i in range(N)]
print("List comprehension: ", time.time() - t0)

#NumPy vectorized
import numpy as np
a_np = np.array(a)
b_np = np.array(b) 
t0 = time.time()
c_np = a_np * b_np
print("NumPy vectorized: ", time.time() - t0)

List comprehension:  0.6437075138092041
NumPy vectorized:  0.023998260498046875


# 5. Numpy Basics

## 5.1. Importing NumPy

To use NumPy, we import it using the standard alias `np`.

In [3]:
import numpy as np

## 5.2. Creating NumPy Arrays

#### 5.2.1. From Python Lists

In [4]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

#### 5.2.2. 2D Array (Matrix)

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

####  5.2.3. Using 'arange', 'zeros', 'ones', 'full', 'empty'

In [11]:
np.arange(10)  # 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros((2,3))   # 2x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3, 3))    # 3x3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((2, 2), 7)    # 2x2 matrix filled with 7

array([[7, 7],
       [7, 7]])

In [97]:
np.empty((2, 3))    # Creates an array with uninitialized values (whatever is in memory).

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [1.48539705e-313, 1.90979621e-313, 2.33419537e-313]])

(Fast, but values are random garbage)

#### 5.2.4. Sequence Generators

Generate evenly spaced numbers.

In [15]:
np.linspace(1, 5, 10)    # 10 values between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Common use: evaluating functions at many points.

In [101]:
from numpy import pi
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)

## 5.3. Array Properties

Useful attributes for understanding array structure.

- arr.shape
- arr.ndim
- arr.size
- arr.dtype
- arr.itemsize

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
arr.shape    # dimensions (rows, columns)

(2, 3)

In [19]:
arr.ndim     # number of dimensions

2

In [20]:
arr.size    # total number of elements

6

In [21]:
arr.dtype    # data type of elements

dtype('int32')

You can specify dtype.

In [98]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
arr.itemsize    # size of one element in bytes

4

## 5.4. Reshaping Arrays

Change shape without changing data.
- arr.reshape()

In [24]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
b.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 5.5. Indexing and Slicing

Works similar to Python lists, but more powerful.

In [41]:
a = np.array([10, 20, 30, 40, 50])

a[0]    # first element

10

In [42]:
a[-1]    # last element

50

In [44]:
a[1: 4]    # slice

array([20, 30, 40])

#### 2D indexing

In [37]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
b[0, 0]    # element at row 0, col 0

1

In [45]:
b[1:, 1:]    # submatrix

array([[5, 6],
       [8, 9]])

## 5.6. Basic Mathematical Operations

NumPy performs element-wise operations by default.

#### Elementwise multiplication

In [104]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [105]:
a + b

array([5, 7, 9])

In [106]:
a - b

array([-3, -3, -3])

In [107]:
a * b     # Elementwise multiplication

array([ 4, 10, 18])

In [54]:
a / b

array([0.25, 0.4 , 0.5 ])

In [55]:
a ** 2

array([1, 4, 9])

#### Matrix multiplication

In [108]:
a @ b    # Matrix multiplication

32

In [109]:
a.dot(b)

32

#### Universal Functions (ufuncs)

These apply to each element automatically.
These are all vectorized (element-wise) functions.

In [111]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974])

In [113]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [114]:
10 * np.sin(a)

array([8.41470985, 9.09297427, 1.41120008])

In [115]:
np.add(a, b)

array([5, 7, 9])

## 5.7. Aggregate Functions

Useful for summarizing data.

In [57]:
x = np.array([1, 2, 3, 4, 5])

In [58]:
x.sum()

15

In [59]:
x.mean()

3.0

In [60]:
x.std()

1.4142135623730951

In [61]:
x.min()

1

In [62]:
x.max()

5

In [63]:
x.argmax    # gives the index of the maximum value

4

In [65]:
x.argmin()    # gives the index of the minimum value

0

## 5.8. Boolean Indexing (Filtering)

Select elements based on condition

In [68]:
arr = np.array([10, 30, 50, 70, 90])

arr[arr>50]   # only elements > 50

array([70, 90])

## 5.9. Broadcasting (Basic Introduction)

NumPy automatically expands smaller arrays to match the shape of larger arrays.

In [71]:
a = np.array([1, 2, 3])
b = 2

a*b      # scalar -> broadcasted

array([2, 4, 6])

## 5.10. Stacking Arrays (Vector Stacking)

Combine arrays vertically and horizontally.

In [117]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

#### Horizontal Stack: side-by-side

In [119]:
np.hstack([x, y])    

array([1, 2, 3, 4, 5, 6])

#### Vertical Stack: One above the other

In [120]:
np.vstack([x, y])    

array([[1, 2, 3],
       [4, 5, 6]])

#### Depth Stack : Adds a new 3rd dimension

In [121]:
np.dstack([x, y])

array([[[1, 4],
        [2, 5],
        [3, 6]]])

#### Column Stack: Converts 1D arrays to columns, then stacks

In [122]:
np.column_stack([x, y])

array([[1, 4],
       [2, 5],
       [3, 6]])

## 5.11. Copy vs View

- 'copy()' creates a new array (changes won't affect original)
- 'view()' or slicing creates a view (linked to original) 

In [82]:
a = np.array([1, 100, 3, 4])
a

array([  1, 100,   3,   4])

In [83]:
c = a.copy()    # copy 
c[1] = 999    # modify copy

In [84]:
print(a)    # original array remains same
print(c) 

[  1 100   3   4]
[  1 999   3   4]


In [87]:
a = np.array([1, 2, 3, 4])
b = a[1:3]   # view
b[0] = 100    # modify view

print(a)    # original array changes!
print(b)

[  1 100   3   4]
[100   3]


# 6. Random Module Basics

#### NumPy Random Module

The numpy.random module helps you generate random numbers, useful in simulations, ML, testing, and data generation.

#### 1. np.random.rand()

Generates random floats between 0 and 1 (uniform distribution).

In [89]:
np.random.rand(3, 3)   # random floats

array([[0.325387  , 0.43144816, 0.37671829],
       [0.36834426, 0.54244026, 0.34250399],
       [0.65972591, 0.48085284, 0.09892774]])

#### 2. np.random.randint()

Generates random integers within a range.

In [91]:
np.random.randint(1, 10, 5)    # random integers

array([8, 5, 6, 3, 2])

#### 3. np.random.randn()

Generates numbers from a standard normal distribution
(mean = 0, std = 1).

In [92]:
np.random.randn(4)    # Gaussian distribution

array([-0.79199989, -1.92576756,  0.32034463, -2.21911274])

# 7. Summary

- NumPy is faster and more memory-efficient than Python lists.
- Vectorization removes Python loops.
- Broadcasting expands arrays automatically.
- NumPy provides math, stats, linear algebra and random functions.
- It is the foundation for Pandas, SciPy, and all ML libraries.